language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t yeasy/simple-web:test -t yeasy/simple-web:latest -f ./Dockerfile .

deploy:
  provider: heroku
  api_key:
    secure: $"HEROKU_API_KEY"
    
after_deploy:
  - echo 'ready?'