language: generic
sudo: required
services:
    - docker

before_install:
    - sudo gem install travis
    - docker build -t yeasy/simple-web:test -t yeasy/simple-web:latest -f ./Dockerfile .

before_deploy:
  - travis encrypt --add deploy.api_key $"HEROKU_API_KEY"

deploy:
  provider: heroku
after_deploy:
  - echo 'ready?'