language: generic
sudo: required
services:
    - docker

before_install:
    - docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com

#script:
# run tests in docker container.
script:
    - docker build -t registry.heroku.com/${HEROKU_APP_NAME}/web -f ./Dockerfile .
    - docker push registry.heroku.com/${HEROKU_APP_NAME}/web
    - ./deploy.sh

# deploy:
#     provider: script
#     script: bash ./deploy.sh
#     on:
#         branch: master