sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
#before_install:
    # - sudo snap install --classic heroku
    # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # - heroku login -i 


# deploy:
#     provider: script
#     script: bash ./deploy.sh
#     on:
#       branch: master
deploy:
    provider: heroku
    api_key:
        secure: $"HEROKU_API_TOKEN"
    before_deploy: bash ./before-deploy.sh
    on:
      branch: master