language: generic
sudo: required
services:
    - docker

before_install:
    - docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
    - docker build -t yeasy/simple-web:test -t yeasy/simple-web:latest -f ./Dockerfile .