sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)

deploy:
    provider: heroku
    api_key:
        secure: $"HEROKU_API_TOKEN"
    before_deploy: bash ./before-deploy.sh
    on:
      branch: master